name: sedac-env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - opencv
  - pip
  - pip:
    - setuptools-rust
    - openai-whisper
    - torchinfo